services:
  eventhub-db:
    container_name: eventhub-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - eventhub_pg_data:/data/postgres
      - ./init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init-multiple-dbs.sql
    ports:
      - "5332:5432"
    networks:
      - eventhub-network
    restart: unless-stopped

  eventhub-auth:
    container_name: eventhub-keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://eventhub-db:5432/keycloak_db
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - eventhub_kc_data:/opt/keycloak/data
    ports:
      - "9090:8080"
    depends_on:
      - eventhub-db
    networks:
      - eventhub-network
    restart: unless-stopped
    command:
      - "start-dev"

  eventhub-app:
    image: zyadtaha/eventhub
    container_name: eventhub-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://eventhub-db:5432/eventhub_prod
    ports:
      - "8080:8080"
    depends_on:
      - eventhub-db
      - eventhub-auth
    networks:
      - eventhub-network
    restart: unless-stopped
    env_file:
      - .env

networks:
  eventhub-network:
    driver: bridge
volumes:
  eventhub_pg_data:
    name: eventhub-postgres-data
  eventhub_kc_data:
    name: eventhub-keycloak-data