spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/eventhub_dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true