spring:
  application:
    name: EventHub
  profiles:
    active: dev
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: '${ISSUER_URI}'
        jwk-set-uri: ${spring.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  mail:
    host: smtp.gmail.com
    port: '587'
    username: '${EMAIL_USERNAME}'
    password: '${EMAIL_PASSWORD}'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  auth:
    converter:
      resource-id: event-hub
      principal-attribute: preferred_username
stripe:
  api:
    key: '${STRIPE_API_KEY}'
springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    filter: true