###
GET http://localhost:8080/venues
###
POST http://localhost:8080/venues
Content-Type: application/json

{
  "name": "Villa",
  "type": "Private",
  "location": "Cairo, Egypt",
  "minCapacity": 1,
  "maxCapacity": 100,
  "imageUrls": [],
  "pricePerHour": 250
}

###
PUT http://localhost:8080/venues/2
Content-Type: application/json

{
  "name": "Updated Villa",
  "type": "Private",
  "location": "Cairo, Egypt",
  "minCapacity": 1,
  "maxCapacity": 150,
  "imageUrls": [],
  "pricePerHour": 300
}

###
DELETE http://localhost:8080/venues/1